### PR TITLE
Added a new app idea: math editor for students

### PR DESCRIPTION
**Pull request by TatuLaras**
Hi!

Thought it would be a cool idea to add an app that would be useful to students like me. The isn't that hard to implement but still requires some knowledge of web or desktop programming so I put on intermediate.

### CODE REVIEW

**Comment by florinpop17** [comment]
This is a very good idea @TatuLaras!
Could you please link the project in the main README.md file? (add it into the table)

**Comment by TatuLaras** [comment]
Should be linked now 👍

**Comment by florinpop17** [comment]
Awesome! Good job!

**Comment by LilacReba** [comment]
hai
I would like to suggest an idea for this math editor idea. This idea is beneficial for many students. All the features added will be helpful too. I would like to add a new feature to this idea. It will be great to add features that can add charts and graphs to the editor.

**Pull request merged**
