### PR TITLE
Add Todo App

### PR DESCRIPTION
**Pull request by SafdarJamal**
Add My Todo App as a Example Project.

### CODE REVIEW

**Comment by florinpop17** [comment]
Hey @SafdarJamal! Thanks for the addition. Is there a way you could host it somewhere live so people can see it?

**Comment by SafdarJamal** [comment]
Already hosted on github pages and the url is available in repo description.

https://safdarjamal.github.io/todo-app/

**Comment by florinpop17** [comment]
Great. Add the live link then in the examples section.

**Comment by SafdarJamal** [comment]
@florinpop17 Live link added.

**Pull request merged**
