### PR TITLE
Weather App

### PR DESCRIPTION
**Pull request by akwetey**
Weather application with plain javaScript and external libraries like axios and bootstrap.

### CODE REVIEW

**Comment by florinpop17** [comment]
Awesome! Could you also add it into one of the tiers? (Maybe in tier 1)

**Comment by akwetey** [comment]
Great! I will do  that.

**Comment by florinpop17** [comment]
Sorry, it's not ok now. You can leave it in tier 1 only, and make sure you edit the root README.md where is the table with all the projects, and add it there (in the list). Makes sense?

**Comment by akwetey** [comment]
Sure makes sense.

**Comment by florinpop17** [comment]
Thank you!!

**Pull request merged**
