### PR TITLE
calendar-app idea

### PR DESCRIPTION
**Pull request by SiddharthVarshney**

### CODE REVIEW

**Comment by florinpop17** [comment]
Hmmm... I don't think that this is a beginner project. It's more like an advanced one.

**Comment by SiddharthVarshney** [comment]
> Hmmm... I don't think that this is a beginner project. It's more like an advanced one.

Yeah, considering the advanced features it will become a tier 3 level project.
So I am changing the Tier to level 3

**Comment by SiddharthVarshney** [comment]
@florinpop17 can you review my pr again

**Comment by florinpop17** [comment]
Please put it alphabetically

**Comment by florinpop17** [comment]
Thank you for your work @SiddharthVarshney !

**Pull request merged**
