### PR TITLE
Project: Movie Database App Add

### PR DESCRIPTION
**Pull request by oliver-gomes**
- Project file added with all info as requested
- Project title added on tier 3 Advance on main Readme

Hope this looks good, Thanks!

### CODE REVIEW

**Comment by oliver-gomes** [comment]
@florinpop17 Btw, I had prettier on VSCode so guess it changed some of the spacing too

**Comment by florinpop17** [comment]
You have some conflicts. Could you resolve them? Also, make sure prettier doesn't change a lot of stuff!

**Comment by oliver-gomes** [comment]
@florinpop17 conflict resolved, Thanks will have head up on prettier

**Comment by florinpop17** [comment]
There are conflicts left. Could you fix them?

**Comment by oliver-gomes** [comment]
@florinpop17 This should be good to go now!

**Comment by florinpop17** [comment]
Merged! Thank you!

**Pull request merged**
